### ISSUE TITLE
FCB 'EnableRegionalDisco' is disabled

### ISSUE THREAD

**Issue by maeg02** [tsharp/D365DeveloperExtensions#7] opened 2021-06-10 04:26 UTC
We are now unable to connect to our organizations using the web resource deployer, this is the error message
FCB 'EnableRegionalDisco' is disabled

**Comment by maeg02** [comment] 2021-06-10 04:26
Complete error message:
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 2021-06-10
Time	: 06:19:16
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.DiscoveryWebProxyClient.<>c__DisplayClass4_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.DiscoveryWebProxyClient.ExecuteCore(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

Source	: mscorlib
Method	: HandleReturnMessage
Date	: 2021-06-10
Time	: 06:20:06
Error	: FCB 'EnableRegionalDisco' is disabled
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.DiscoveryWebProxyClient.<>c__DisplayClass4_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.DiscoveryWebProxyClient.ExecuteCore(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, X509Certificate2 loginCertificate, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, ClientCredentials clientCredentials, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryOAuthDiscoveryServer(Uri discoServer, ClientCredentials liveCreds, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

**Comment by maeg02** [comment] 2021-06-10 04:29
might this be due to that Regional Discovery is now deprecated and remove?
https://docs.microsoft.com/en-us/power-platform/important-changes-coming#regional-discovery-service-is-deprecated

**Comment by duckz0r** [comment] 2021-06-22 11:36
Since the regional discovery service has been deprecated, this extension no longer works.
XRMToolbox has switched to a Microsoft Login Control, and has this working. When will this be fixed?

**Comment by bilal684** [comment] 2021-07-07 17:48
Same thing here. Looking into a fix to be able to use that extension again as it is indeed very useful.

**Comment by bilal684** [comment] 2021-07-29 20:14
I created a PR that fixes this issue. Awaiting review of @tsharp .

**Comment by tsharp** [comment] 2021-07-30 03:23
@bilal684 thsnk you for this pr, I’ll pull these changes and verify the fix.

**Comment by bilal684** [comment] 2021-07-30 03:26
You're welcome, thank you for the quick follow-up 🙂

**Comment by SteveTe** [comment] 2021-09-16 01:12
Hi there any update on a release date for the fix?

**Comment by bilal684** [comment] 2021-09-17 13:44
@SteveTe Should be fixed now, changes were approved yesterday :)

**Comment by tsharp** [comment] 2021-09-18 16:50
I'll have a new build pushed to the marketplace this weekend!

**Comment by SteveTe** [comment] 2021-09-19 23:14
Thanks for the update Travis.

Your application is fantastic and really helps development.

Best Regards,

Steve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tsharp** [comment] 2021-09-20 07:16
2015/2017 and 2019 are all still in support but it looks like the manifest definitions changed for 2022 and aren't compatible for the time being. I'll open an issue for that and see about adding support for that in :)

Also - the latest version has been released in  github and in the marketplace [2.0.21263.610](https://marketplace.visualstudio.com/items?itemName=tsharp.D365DeveloperExtensions) - please let me know if you run into any issues with this build .

**Closed by tsharp** 2021-09-20 07:16 UTC
Labels: bug, dependencies

**Comment by SteveTe** [comment] 2021-09-20 07:28
I can confirm that it's working now!

Many Thanks.
